### ISSUE TITLE
Version 2.0.0 throws exeptions

### ISSUE THREAD

**Issue by cruiser252** [Appdynamics/nginx-monitoring-extension#6]
Hi,

we are using heavily Nginx Plus and want to update to R17. So I tried Version 2.0.0.
After starting the machine agent, it throws errors:

[Monitor-Task-Thread5] 14 Dec 2018 15:40:47,455 ERROR StatsExtractor - Unexpected error while collecting metrics for server zones stat
org.json.JSONException: JSONObject["path"] is not a JSONObject.
        at org.json.JSONObject.getJSONObject(JSONObject.java:577)
        at com.appdynamics.monitors.nginx.statsExtractor.ServerZoneStatsExtractor.extractStats(ServerZoneStatsExtractor.java:43)
        at com.appdynamics.monitors.nginx.JSONResponseParser.run(JSONResponseParser.java:78)
        at com.appdynamics.extensions.MonitorThreadPoolExecutor$2.run(MonitorThreadPoolExecutor.java:102)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[Monitor-Task-Thread15] 14 Dec 2018 15:40:47,460 ERROR StatsExtractor - Unexpected error while collecting metrics for upstream stat
org.json.JSONException: JSONObject["path"] is not a JSONObject.
        at org.json.JSONObject.getJSONObject(JSONObject.java:577)
        at com.appdynamics.monitors.nginx.statsExtractor.UpstreamsStatsExtractor.extractStats(UpstreamsStatsExtractor.java:43)
        at com.appdynamics.monitors.nginx.JSONResponseParser.run(JSONResponseParser.java:78)
        at com.appdynamics.extensions.MonitorThreadPoolExecutor$2.run(MonitorThreadPoolExecutor.java:102)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[Monitor-Task-Thread10] 14 Dec 2018 15:40:47,461  WARN StatsFactory - No matching class in the factory forkeyvals
[Monitor-Task-Thread3] 14 Dec 2018 15:40:47,478 ERROR StatsExtractor - Unexpected error while collecting metrics for upstream stat
com.appdynamics.extensions.util.AssertUtils$ValidationException:
        at com.appdynamics.extensions.util.AssertUtils.assertNotNull(AssertUtils.java:28)
        at com.appdynamics.extensions.metrics.Metric.<init>(Metric.java:33)
        at com.appdynamics.extensions.metrics.Metric.<init>(Metric.java:49)
        at com.appdynamics.monitors.nginx.statsExtractor.UpstreamsStatsExtractor.collectUpStreamMetrics(UpstreamsStatsExtractor.java:94)
        at com.appdynamics.monitors.nginx.statsExtractor.UpstreamsStatsExtractor.extractStats(UpstreamsStatsExtractor.java:54)
        at com.appdynamics.monitors.nginx.JSONResponseParser.run(JSONResponseParser.java:78)
        at com.appdynamics.extensions.MonitorThreadPoolExecutor$2.run(MonitorThreadPoolExecutor.java:102)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Can you please fix it? Or what is wrong with my installation?

Best regards,
Sven

**Comment by prashmeh** [comment]
Hi Sven,

Please create a zendesk ticket(help@appdynamics.com) with all the details and extension's debug logs. Also please share in the ticket the responses for the following APIs. 

```
http://your_nginx_server.com/api/3/http/upstreams/
http://your_nginx_server.com/api/3/http/server_zones/
```

Meanwhile, We will also try to reproduce this at our end.


Regards
Prashant

**Comment by cruiser252** [comment]
Hi Prashant,

I tried it again, as there was an update to fix merge conflicts.... It works now. Can you tell me, when the release will be final?

Best regards,
Sven

**Comment by prashmeh** [comment]
Hi @cruiser252 

Good to know that it worked. We should be able to publish and release it on our [Community-Exchange page](https://www.appdynamics.com/community/exchange/) in a week or so.

Regards
Prashant
