### ISSUE TITLE
Issue wile setting up nginx monitor in RHEL7. Agent Version 4.4.0

### ISSUE THREAD

**Issue by nurawat** [Appdynamics/nginx-monitoring-extension#7]
[system-thread-0] 12 Apr 2019 15:35:37,355  INFO JavaTaskCreator - Task classpath not specified,System classpath will be used.
[system-thread-0] 12 Apr 2019 15:35:37,356 ERROR JavaTaskCreator - Could not load/instantiate the Java Task Main class for Java task [Nginx Monitor Run Task]
java.lang.NullPointerException
        at com.singularity.ee.agent.systemagent.task.JavaTaskCreator.createJavaTask(JavaTaskCreator.java:65)
        at com.singularity.ee.agent.systemagent.components.monitormanager.managed.MonitorTaskRunner.createTask(MonitorTaskRunner.java:74)
        at com.singularity.ee.agent.systemagent.components.monitormanager.managed.PeriodicTaskRunner.<init>(PeriodicTaskRunner.java:41)
        at com.singularity.ee.agent.systemagent.components.monitormanager.managed.ManagedMonitorDelegate.setupEnvTask(ManagedMonitorDelegate.java:254)
        at com.singularity.ee.agent.systemagent.components.monitormanager.managed.ManagedMonitorDelegate.initializeMonitor(ManagedMonitorDelegate.java:211)
        at com.singularity.ee.agent.systemagent.components.monitormanager.NodeMonitorManager.readConfig(NodeMonitorManager.java:180)
        at com.singularity.ee.agent.systemagent.components.monitormanager.NodeMonitorManager.startAllMonitors(NodeMonitorManager.java:261)
        at com.singularity.ee.agent.systemagent.components.monitormanager.NodeMonitorManager.<init>(NodeMonitorManager.java:78)
        at com.singularity.ee.agent.systemagent.components.monitormanager.AgentMonitorManager.<init>(AgentMonitorManager.java:62)
        at com.singularity.ee.agent.systemagent.Agent.setupMonitorManager(Agent.java:449)
        at com.singularity.ee.agent.systemagent.Agent.startServices(Agent.java:358)
        at com.singularity.ee.agent.systemagent.SystemAgent.startServices(SystemAgent.java:68)
        at com.singularity.ee.agent.systemagent.Agent.start(Agent.java:343)
        at com.appdynamics.agent.sim.legacy.DefaultLegacyAgentRegistrationStateManager$1.run(DefaultLegacyAgentRegistrationStateManager.java:80)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by satish-m** [comment]
@nurawat please go through this [Troubleshooting guide](https://community.appdynamics.com/t5/Knowledge-Base/How-do-I-troubleshoot-missing-custom-metrics-or-extensions/ta-p/28695) and contact support team if you are still facing issues.
