### ISSUE TITLE
Cannot be used with Machine Agent 20.7.0.2694

### ISSUE THREAD

**Issue by hypery2k** [Appdynamics/nginx-monitoring-extension#9]
Cannot start the extension on newer machine agents:
```
$ java -jar /var/lib/appdynamics/server-agent/monitors/NginxMonitor/nginx-monitoring-extension.jar

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[INFO] The launch command is [/usr/local/jdk8u232-b09/jre/bin/java, -cp, /var/lib/appdynamics/server-agent/machineagent.jar:/var/lib/appdynamics/server-agent/monitors/NginxMonitor/nginx-monitoring-extension.jar, com.appdynamics.extensions.workbench.WorkBenchServer]
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/log4j/Layout
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: org.apache.log4j.Layout
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 7 more
```

Any chance to get an update?

**Comment by saxenaabhi142** [comment]
Hi, 
Can you please let us know which version of nginx extension are you running with machine agent 20.7

**Comment by hypery2k** [comment]
2.0.0

**Comment by saxenaabhi142** [comment]
Hi, 
The version of extension you are using is old.

Kindly use the latest version of extension (v2.2.0) from below link:
https://www.appdynamics.com/community/exchange/extension/nginx-and-nginx-plus-monitoring-extension/

Carefully go through the prerequisite, installation and configuration guidelines while using the extension.

**Comment by hypery2k** [comment]
thanks, that solved it

**Comment by saxenaabhi142** [comment]
Glad to hear that it is solved.
Thanks for the update. We closing this issue.
